### ISSUE TITLE
Borders on maximized windows

### ISSUE THREAD

**Issue by nclarius** [Prayag2/kde_onedark#1]
Thank you for this theme, the window decorations with the colored borders are very useful to tell the active window apart when not using title bars.  

I would like to have borders around maximized windows too, so that I can identify which of two maximized windows on multiple screens is the active one. However, even though in `~/.config/kwinrc` I set `BorderlessMaximizedWindows=false`, window borders disappear when a window gets maximized. I can find no matching setting in `~/.local/share/aurorae/themes/One-Dark-Blue/One-Dark-Bluerc` either.

Is it possible with this theme to have borders around a window when it is maximized, and if so, how?

Thanks.

Operating System: Arch Linux
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.4-arch1-1 (64-bit)
Graphics Platform: X11

**Comment by Prayag2** [comment]
Are you using Krohnkite?

**Comment by nclarius** [comment]
No, just KWin without a tiling extension.

**Comment by Prayag2** [comment]
Can you share a screenshot or a video? I'm not able to reproduce this issue.

**Comment by nclarius** [comment]
https://user-images.githubusercontent.com/13196860/144064179-2bfa5c49-869a-4f67-ac88-fbefc7b79c6d.mp4

**Comment by nclarius** [comment]
I wrote myself a custom maximize function with a KWin script that sets the window geometry equal to the client area geometry; don't know why that makes a difference, but now I get my borders, so the problem has resolved itself for me.
