### ISSUE TITLE
Invisible border without blur

### ISSUE THREAD

**Issue by nclarius** [Prayag2/kde_onedark#2]
Me again, opening a separate issue for this one.

For inactive windows I would like to have no border at all, because with some applications I use a light and with others a dark theme so settling on one inactive window border color will always make some windows have strangely contrasting borders.

So I edited the decoration svg to set the color to 0% opacity for the inactive frame. Now the border does sort of become transparent, but it still leaves a blurry outline:
![Screenshot_2021-11-30_15-13-41](https://user-images.githubusercontent.com/13196860/144063518-d44e19dd-19a2-4726-b5dc-8e2f931b34c4.png)

That might be a sibling of the infamous korners bug; switching to a different compositor (picom) as some suggest did not solve it for me.  

It's not a huge usability problem, just an aesthetic inconvenience, but do you happen to have an idea where this comes from and how to achieve truly invisible borders?

**Comment by Prayag2** [comment]
I don't think this is related to the korners bug. Afaik having borders and no-borders at the same time is not possible at the moment. You can disable blur for the time being.

**Comment by nclarius** [comment]
Okay, thanks.
